### ISSUE TITLE
Adding Token binding to a function prevents functions host from initializing.

### ISSUE THREAD

**Issue by luciobemquerer** [Azure/azure-functions-microsoftgraph-extension#46]
This error happens whenever I add a Token binding to any function in the App. I hit this same error in 3 different Function Apps, in 3 different tenants, by using the portal. And managed to reproduce locally using "func.exe".

All I had to do to reproduce the error was:
1. Create a new Functions App in `beta` version.
2. Install the Token extension Microsoft.Azure.WebJobs.Extensions.AuthTokens
3. Add a token parameter to a default HttpTrigger function.

Same steps created the same error using the Functions Portal, or using a VS C# Functions App.

```
[30-Mar-18 07:50:44] Loaded custom extension: AuthTokenExtensionConfig from 'referenced by: Method='MsGraphBridge.TokenClass.Run', Parameter='graphToken'.'
[30-Mar-18 07:50:44] A ScriptHost error has occurred
[30-Mar-18 07:50:44] Microsoft.Azure.WebJobs.Extensions.Tokens: Method not found: 'Void Microsoft.Azure.WebJobs.Host.Config.FluentBindingRule`1.BindToInput(Microsoft.Azure.WebJobs.IAsyncConverter`2<!0,!!0>)'.
[30-Mar-18 07:50:44] Stopping Host
```

![image](https://user-images.githubusercontent.com/17251962/38130033-27f0e49c-344d-11e8-8012-15dc2b16d12c.png)

Binding:
```
{
  "bindings": [
    {
      "authLevel": "function",
      "name": "req",
      "type": "httpTrigger",
      "direction": "in",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "name": "$return",
      "type": "http",
      "direction": "out"
    },
    {
      "type": "token",
      "name": "token",
      "resource": "https://graph.microsoft.com",
      "identity": "UserFromRequest",
      "direction": "in"
    }
  ]
}
```

[MsGraphBridge.deps.txt](https://github.com/Azure/azure-functions-microsoftgraph-extension/files/1863035/MsGraphBridge.deps.txt)

**Comment by ConnorMcMahon** [comment]
This is related to [this issue](https://github.com/Azure/azure-functions-host/issues/2448#issuecomment-377416573). The beta3 nuget will be released today that fixes this issue, and I will post update instructions for people on earlier versions. Starting on Monday, all future Portal installations of the token or graph binding should have this version.

**Comment by brspnnggrt** [comment]
I had this issue last week. This week however, I can't seem to add graph tokens anymore as input in the azure function. Both in the current beta release (2.0.11651.0) and the previous version (2.0.11587-alpha).
I see the new version of the [graph bindings on Nuget](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.MicrosoftGraph/1.0.0-beta3), but I can only manually install it via extensions.csproj which doesn't seem to work either in the console of azure functions (not to mention it ends with bad request). I have not yet tried to deploy from visual studio or from vs code cli.

**Comment by ConnorMcMahon** [comment]
@brspnnggrt, We couldn't update the Portal templates on time to get the fix out, so we just removed them. They will be back in there in the next release (about 2 weeks). Deploying from Visual Studio and the Azure Functions CLI should both work, but so should installing manually via extensions.csproj. 

Can you give me the error output when you try to run it?

**Comment by brspnnggrt** [comment]
I got it to work using the Azure Functions CLI. I already removed the previous function, but I didn't see anything else but "Bad Request" in the Azure Console. Even stranger, it did create the binaries in the /bin folder, but it still wouldn't work.

**Comment by brspnnggrt** [comment]
After a certain time period, the function stops working and I get the following response: 

`2018-04-06T13:24:47.145 [Error] System.Private.CoreLib: Exception while executing function: Functions.getCalendar. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'graphToken'. Microsoft.IdentityModel.Clients.ActiveDirectory: AADSTS70002: Error validating credentials. AADSTS50013: Assertion is not within its valid time range.
Trace ID: e9c4c023-b531-45a4-a63c-be4f2e621000
Correlation ID: f5886be0-6846-484f-9d4b-b10711a8047c
Timestamp: 2018-04-06 13:24:46Z. Microsoft.IdentityModel.Clients.ActiveDirectory:  Response status code does not indicate success: 400 (BadRequest). {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS50013: Assertion is not within its valid time range.\r\nTrace ID: e9c4c023-b531-45a4-a63c-be4f2e621000\r\nCorrelation ID: f5886be0-6846-484f-9d4b-b10711a8047c\r\nTimestamp: 2018-04-06 13:24:46Z","error_codes":[70002,50013],"timestamp":"2018-04-06 13:24:46Z","trace_id":"e9c4c023-b531-45a4-a63c-be4f2e621000","correlation_id":"f5886be0-6846-484f-9d4b-b10711a8047c"}.
2018-04-06T13:24:47.489 [Error] Executed 'Functions.getCalendar' (Failed, Id=ae18d8ff-2e42-4f0e-a761-bbc9c33bbf9f)`

The function uses the cookie to authenticate. Since I can open any other page from azure/office365, I am assuming my cookie is still valid? Is there any solution for this? 

Thanks

Gert

**Comment by ConnorMcMahon** [comment]
@brspnnggrt, what identity mode is your token set for?

**Comment by brspnnggrt** [comment]
UserFromRequest @ConnorMcMahon

**Comment by ConnorMcMahon** [comment]
I'm closing this issue, as using beta3 resolves this. @brspnnggrt, I'm going to move your problem to a different issue.
